### ISSUE TITLE
Windows get disconnected from the network after joining docker swarm 

### ISSUE THREAD

**Issue by hgontijo** [mikegcoleman/hybrid-workshop#4]
Thanks for providing this fully detailed workshop. I'm facing a problem where my Windows machine gets inaccessible right after it joins the Docker swarm:`docker swarm join --token <token> <ip>:2377`.

The VM is running on AWS, here's their screenshot showing a network issue:
![screen shot 2017-08-14 at 5 00 02 pm](https://user-images.githubusercontent.com/300443/29296972-7c73d054-8112-11e7-86ea-fb4c41c0eeb4.png)

The EC2 status check shows:
> Instance reachability check failed at August 14, 2017 at 4:58:00 PM UTC-7 (6 minutes ago)

Docker version is 17.03.

Any clue? Thanks.

**Comment by mikegcoleman** [comment]
I ran into this as well, which is why I provision all my stuff on Azure at this point. I've not had a chance to go back to AWS to troubleshoot it - so I don't really have an answer at this point. 

On Azure when you join the cluster, the machine will drop the RDP connection, but you can immediately reconnect. So there is something that happens in the stack, but Azure and AWS handle it differently.

**Comment by hgontijo** [comment]
Thanks for your reply. After running into this issue on AWS, I deployed a Windows 2016 VM on vCenter 6 and the behavior was similar to Azure - after joining the swarm cluster, there's a short network hiccup and it works fine after that. The hybrid setup with a Linux (AWS EC2) container communicating with a Windows (vCenter VM) container worked well for me.
